#
# Quake3 Unix Game Makefile
#
# GNU Make required
#

###
### These paths are where you probably want to change things
###

#The main Quake3 directory
BDIR=..

#This is the game dir
GAMEDIR=baseq3

#Where the source is, assumed to be same directory as this Makefile
SRCDIR=.

#Location of binaries
BINDIR=../bin
LCC=$(BINDIR)/lcc # -lccdir=$(BINDIR)/
Q3ASM=$(BINDIR)/q3asm


#############################################################################
##
## You shouldn't have to touch anything below here
##
#############################################################################

GDIR=$(SRCDIR)/game
CGDIR=$(SRCDIR)/cgame
UIDIR=$(SRCDIR)/ui
Q3UIDIR=$(SRCDIR)/q3_ui

LCCFLAGS=-DQ3_VM -S -Wf-target=bytecode -Wf-g -I$(CGDIR) -I$(GDIR) -I$(UIDIR)
UILCCFLAGS=-DQ3_VM -S -Wf-target=bytecode -Wf-g -I$(CGDIR) -I$(GDIR) -I$(Q3UIDIR)

DO_LCC=$(LCC) $(LCCFLAGS) -o $@ -c $<
DO_UI_LCC=$(LCC) $(UILCCFLAGS) -o $@ -c $<

TARGETS=\
	$(BDIR)/$(GAMEDIR)/vm/cgame.qvm \
	$(BDIR)/$(GAMEDIR)/vm/qagame.qvm \
	$(BDIR)/$(GAMEDIR)/vm/ui.qvm

default: makedir $(TARGETS)

makedir:
	@-mkdir $(GDIR)/vm
	@-mkdir $(CGDIR)/vm
	@-mkdir $(UIDIR)/vm
	@-mkdir $(Q3UIDIR)/vm

#############################################################################
# GAME VM
#############################################################################

##NOTE:  g_main must be first.  Control passes to first function in the vm

GVMASM = \
	$(GDIR)/vm/g_main.asm \
	$(GDIR)/vm/bg_misc.asm \
	$(GDIR)/vm/bg_lib.asm \
	$(GDIR)/vm/bg_pmove.asm \
	$(GDIR)/vm/bg_slidemove.asm \
	$(GDIR)/vm/q_math.asm \
	$(GDIR)/vm/q_shared.asm \
	$(GDIR)/vm/ai_dmnet.asm \
	$(GDIR)/vm/ai_dmq3.asm \
	$(GDIR)/vm/ai_cmd.asm \
	$(GDIR)/vm/ai_team.asm \
	$(GDIR)/vm/ai_main.asm \
	$(GDIR)/vm/ai_chat.asm \
	$(GDIR)/vm/g_active.asm \
	$(GDIR)/vm/g_arenas.asm \
	$(GDIR)/vm/g_bot.asm \
	$(GDIR)/vm/g_client.asm \
	$(GDIR)/vm/g_cmds.asm \
	$(GDIR)/vm/g_combat.asm \
	$(GDIR)/vm/g_items.asm \
	$(GDIR)/vm/g_mem.asm \
	$(GDIR)/vm/g_misc.asm \
	$(GDIR)/vm/g_missile.asm \
	$(GDIR)/vm/g_mover.asm \
	$(GDIR)/vm/g_session.asm \
	$(GDIR)/vm/g_spawn.asm \
	$(GDIR)/vm/g_svcmds.asm \
	$(GDIR)/vm/g_target.asm \
	$(GDIR)/vm/g_team.asm \
	$(GDIR)/vm/g_trigger.asm \
	$(GDIR)/vm/g_utils.asm \
	$(GDIR)/vm/g_weapon.asm \
	$(GDIR)/vm/ai_monster.asm \
	$(GDIR)/vm/mon_grunt.asm

$(BDIR)/$(GAMEDIR)/vm/qagame.qvm : $(GVMASM)
	$(Q3ASM) -o $@ $(GVMASM) $(SRCDIR)/game/g_syscalls.asm

$(GDIR)/vm/ai_chat.asm : $(GDIR)/ai_chat.c; $(DO_LCC) 
$(GDIR)/vm/ai_cmd.asm : $(GDIR)/ai_cmd.c; $(DO_LCC)
$(GDIR)/vm/ai_dmnet.asm : $(GDIR)/ai_dmnet.c; $(DO_LCC) 
$(GDIR)/vm/ai_dmq3.asm : $(GDIR)/ai_dmq3.c; $(DO_LCC) 
$(GDIR)/vm/ai_main.asm : $(GDIR)/ai_main.c; $(DO_LCC) 
$(GDIR)/vm/ai_team.asm : $(GDIR)/ai_team.c; $(DO_LCC) 
$(GDIR)/vm/bg_lib.asm : $(GDIR)/bg_lib.c; $(DO_LCC) 
$(GDIR)/vm/bg_misc.asm : $(GDIR)/bg_misc.c; $(DO_LCC) 
$(GDIR)/vm/bg_pmove.asm : $(GDIR)/bg_pmove.c; $(DO_LCC) 
$(GDIR)/vm/bg_slidemove.asm : $(GDIR)/bg_slidemove.c; $(DO_LCC) 
$(GDIR)/vm/g_active.asm : $(GDIR)/g_active.c; $(DO_LCC) 
$(GDIR)/vm/g_arenas.asm : $(GDIR)/g_arenas.c; $(DO_LCC) 
$(GDIR)/vm/g_bot.asm : $(GDIR)/g_bot.c; $(DO_LCC) 
$(GDIR)/vm/g_client.asm : $(GDIR)/g_client.c; $(DO_LCC) 
$(GDIR)/vm/g_cmds.asm : $(GDIR)/g_cmds.c; $(DO_LCC) 
$(GDIR)/vm/g_combat.asm : $(GDIR)/g_combat.c; $(DO_LCC) 
$(GDIR)/vm/g_items.asm : $(GDIR)/g_items.c; $(DO_LCC) 
$(GDIR)/vm/g_main.asm : $(GDIR)/g_main.c; $(DO_LCC) 
$(GDIR)/vm/g_mem.asm : $(GDIR)/g_mem.c; $(DO_LCC) 
$(GDIR)/vm/g_misc.asm : $(GDIR)/g_misc.c; $(DO_LCC) 
$(GDIR)/vm/g_missile.asm : $(GDIR)/g_missile.c; $(DO_LCC) 
$(GDIR)/vm/g_mover.asm : $(GDIR)/g_mover.c; $(DO_LCC) 
$(GDIR)/vm/g_session.asm : $(GDIR)/g_session.c; $(DO_LCC) 
$(GDIR)/vm/g_spawn.asm : $(GDIR)/g_spawn.c; $(DO_LCC) 
$(GDIR)/vm/g_svcmds.asm : $(GDIR)/g_svcmds.c; $(DO_LCC) 
$(GDIR)/vm/g_target.asm : $(GDIR)/g_target.c; $(DO_LCC) 
$(GDIR)/vm/g_team.asm : $(GDIR)/g_team.c; $(DO_LCC) 
$(GDIR)/vm/g_trigger.asm : $(GDIR)/g_trigger.c; $(DO_LCC) 
$(GDIR)/vm/g_utils.asm : $(GDIR)/g_utils.c; $(DO_LCC) 
$(GDIR)/vm/g_weapon.asm : $(GDIR)/g_weapon.c; $(DO_LCC) 
$(GDIR)/vm/mon_grunt.asm : $(GDIR)/mon_grunt.c; $(DO_LCC) 
$(GDIR)/vm/q_math.asm : $(GDIR)/q_math.c; $(DO_LCC) 
$(GDIR)/vm/q_shared.asm : $(GDIR)/q_shared.c; $(DO_LCC) 
$(GDIR)/vm/ai_monster.asm : $(GDIR)/ai_monster.c; $(DO_LCC) 
#############################################################################
# CGAME VM
#############################################################################

##NOTE:  cg_main must be first.  Control passes to first function in the vm

CGVMASM = \
	$(CGDIR)/vm/cg_main.asm \
	$(CGDIR)/vm/cg_consolecmds.asm \
	$(CGDIR)/vm/cg_draw.asm \
	$(CGDIR)/vm/cg_drawtools.asm \
	$(CGDIR)/vm/cg_effects.asm \
	$(CGDIR)/vm/cg_ents.asm \
	$(CGDIR)/vm/cg_event.asm \
	$(CGDIR)/vm/cg_info.asm \
	$(CGDIR)/vm/cg_localents.asm \
	$(CGDIR)/vm/cg_marks.asm \
	$(CGDIR)/vm/cg_players.asm \
	$(CGDIR)/vm/cg_playerstate.asm \
	$(CGDIR)/vm/cg_predict.asm \
	$(CGDIR)/vm/cg_scoreboard.asm \
	$(CGDIR)/vm/cg_servercmds.asm \
	$(CGDIR)/vm/cg_snapshot.asm \
	$(CGDIR)/vm/cg_view.asm \
	$(CGDIR)/vm/cg_weapons.asm \
	$(CGDIR)/vm/bg_slidemove.asm \
	$(CGDIR)/vm/bg_pmove.asm \
	$(CGDIR)/vm/bg_lib.asm \
	$(CGDIR)/vm/bg_misc.asm \
	$(CGDIR)/vm/q_math.asm \
	$(CGDIR)/vm/q_shared.asm

$(BDIR)/$(GAMEDIR)/vm/cgame.qvm : $(CGVMASM)
	$(Q3ASM) -o $@ $(CGVMASM) $(CGDIR)/cg_syscalls.asm

$(CGDIR)/vm/cg_main.asm : $(CGDIR)/cg_main.c; $(DO_LCC)
$(CGDIR)/vm/cg_consolecmds.asm : $(CGDIR)/cg_consolecmds.c; $(DO_LCC)
$(CGDIR)/vm/cg_draw.asm : $(CGDIR)/cg_draw.c; $(DO_LCC)
$(CGDIR)/vm/cg_drawtools.asm : $(CGDIR)/cg_drawtools.c; $(DO_LCC)
$(CGDIR)/vm/cg_effects.asm : $(CGDIR)/cg_effects.c; $(DO_LCC)
$(CGDIR)/vm/cg_ents.asm : $(CGDIR)/cg_ents.c; $(DO_LCC)
$(CGDIR)/vm/cg_event.asm : $(CGDIR)/cg_event.c; $(DO_LCC)
$(CGDIR)/vm/cg_info.asm : $(CGDIR)/cg_info.c; $(DO_LCC)
$(CGDIR)/vm/cg_localents.asm : $(CGDIR)/cg_localents.c; $(DO_LCC)
$(CGDIR)/vm/cg_marks.asm : $(CGDIR)/cg_marks.c; $(DO_LCC)
$(CGDIR)/vm/cg_players.asm : $(CGDIR)/cg_players.c; $(DO_LCC)
$(CGDIR)/vm/cg_playerstate.asm : $(CGDIR)/cg_playerstate.c; $(DO_LCC)
$(CGDIR)/vm/cg_predict.asm : $(CGDIR)/cg_predict.c; $(DO_LCC)
$(CGDIR)/vm/cg_scoreboard.asm : $(CGDIR)/cg_scoreboard.c; $(DO_LCC)
$(CGDIR)/vm/cg_servercmds.asm : $(CGDIR)/cg_servercmds.c; $(DO_LCC)
$(CGDIR)/vm/cg_snapshot.asm : $(CGDIR)/cg_snapshot.c; $(DO_LCC)
$(CGDIR)/vm/cg_view.asm : $(CGDIR)/cg_view.c; $(DO_LCC)
$(CGDIR)/vm/cg_weapons.asm : $(CGDIR)/cg_weapons.c; $(DO_LCC)
$(CGDIR)/vm/bg_slidemove.asm : $(GDIR)/bg_slidemove.c; $(DO_LCC)
$(CGDIR)/vm/bg_pmove.asm : $(GDIR)/bg_pmove.c; $(DO_LCC)
$(CGDIR)/vm/bg_lib.asm : $(GDIR)/bg_lib.c; $(DO_LCC)
$(CGDIR)/vm/bg_misc.asm : $(GDIR)/bg_misc.c; $(DO_LCC)
$(CGDIR)/vm/q_math.asm : $(GDIR)/q_math.c; $(DO_LCC)
$(CGDIR)/vm/q_shared.asm : $(GDIR)/q_shared.c; $(DO_LCC)

#############################################################################
# UI VM  (base q3_ui)
#############################################################################

##NOTE:  ui_main must be first.  Control passes to first function in the vm

UIVMASM = \
	$(Q3UIDIR)/vm/ui_main.asm \
	$(Q3UIDIR)/vm/ui_gameinfo.asm \
	$(Q3UIDIR)/vm/ui_atoms.asm \
	$(Q3UIDIR)/vm/ui_botladder.asm \
	$(Q3UIDIR)/vm/ui_cinematics.asm \
	$(Q3UIDIR)/vm/ui_connect.asm \
	$(Q3UIDIR)/vm/ui_controls2.asm \
	$(Q3UIDIR)/vm/ui_demo2.asm \
	$(Q3UIDIR)/vm/ui_mfield.asm \
	$(Q3UIDIR)/vm/ui_credits.asm \
	$(Q3UIDIR)/vm/ui_menu.asm \
	$(Q3UIDIR)/vm/ui_ingame.asm \
	$(Q3UIDIR)/vm/ui_confirm.asm \
	$(Q3UIDIR)/vm/ui_setup.asm \
	$(Q3UIDIR)/vm/ui_options.asm \
	$(Q3UIDIR)/vm/ui_display.asm \
	$(Q3UIDIR)/vm/ui_sound.asm \
	$(Q3UIDIR)/vm/ui_network.asm \
	$(Q3UIDIR)/vm/ui_playermodel.asm \
	$(Q3UIDIR)/vm/ui_players.asm \
	$(Q3UIDIR)/vm/ui_playersettings.asm \
	$(Q3UIDIR)/vm/ui_preferences.asm \
	$(Q3UIDIR)/vm/ui_qmenu.asm \
	$(Q3UIDIR)/vm/ui_serverinfo.asm \
	$(Q3UIDIR)/vm/ui_servers2.asm \
	$(Q3UIDIR)/vm/ui_sparena.asm \
	$(Q3UIDIR)/vm/ui_specifyserver.asm \
	$(Q3UIDIR)/vm/ui_sppostgame.asm \
	$(Q3UIDIR)/vm/ui_splevel.asm \
	$(Q3UIDIR)/vm/ui_spskill.asm \
	$(Q3UIDIR)/vm/ui_startserver.asm \
	$(Q3UIDIR)/vm/ui_team.asm \
	$(Q3UIDIR)/vm/ui_video.asm \
	$(Q3UIDIR)/vm/ui_addbots.asm \
	$(Q3UIDIR)/vm/ui_removebots.asm \
	$(Q3UIDIR)/vm/ui_teamorders.asm \
	$(Q3UIDIR)/vm/ui_cdkey.asm \
	$(Q3UIDIR)/vm/ui_mods.asm \
	$(Q3UIDIR)/vm/bg_misc.asm \
	$(Q3UIDIR)/vm/bg_lib.asm \
	$(Q3UIDIR)/vm/q_math.asm \
	$(Q3UIDIR)/vm/q_shared.asm

$(BDIR)/$(GAMEDIR)/vm/ui.qvm : $(UIVMASM)
	$(Q3ASM) -o $@ $(UIVMASM) $(UIDIR)/ui_syscalls.asm

$(Q3UIDIR)/vm/ui_main.asm : $(Q3UIDIR)/ui_main.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_gameinfo.asm : $(Q3UIDIR)/ui_gameinfo.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_atoms.asm : $(Q3UIDIR)/ui_atoms.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_botladder.asm : $(Q3UIDIR)/ui_botladder.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_cinematics.asm : $(Q3UIDIR)/ui_cinematics.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_connect.asm : $(Q3UIDIR)/ui_connect.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_controls2.asm : $(Q3UIDIR)/ui_controls2.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_demo2.asm : $(Q3UIDIR)/ui_demo2.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_mfield.asm : $(Q3UIDIR)/ui_mfield.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_credits.asm : $(Q3UIDIR)/ui_credits.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_menu.asm : $(Q3UIDIR)/ui_menu.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_ingame.asm : $(Q3UIDIR)/ui_ingame.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_confirm.asm : $(Q3UIDIR)/ui_confirm.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_setup.asm : $(Q3UIDIR)/ui_setup.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_options.asm : $(Q3UIDIR)/ui_options.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_display.asm : $(Q3UIDIR)/ui_display.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_sound.asm : $(Q3UIDIR)/ui_sound.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_network.asm : $(Q3UIDIR)/ui_network.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_playermodel.asm : $(Q3UIDIR)/ui_playermodel.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_players.asm : $(Q3UIDIR)/ui_players.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_playersettings.asm : $(Q3UIDIR)/ui_playersettings.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_preferences.asm : $(Q3UIDIR)/ui_preferences.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_qmenu.asm : $(Q3UIDIR)/ui_qmenu.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_serverinfo.asm : $(Q3UIDIR)/ui_serverinfo.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_servers2.asm : $(Q3UIDIR)/ui_servers2.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_sparena.asm : $(Q3UIDIR)/ui_sparena.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_specifyserver.asm : $(Q3UIDIR)/ui_specifyserver.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_sppostgame.asm : $(Q3UIDIR)/ui_sppostgame.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_splevel.asm : $(Q3UIDIR)/ui_splevel.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_spskill.asm : $(Q3UIDIR)/ui_spskill.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_startserver.asm : $(Q3UIDIR)/ui_startserver.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_team.asm : $(Q3UIDIR)/ui_team.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_video.asm : $(Q3UIDIR)/ui_video.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_addbots.asm : $(Q3UIDIR)/ui_addbots.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_removebots.asm : $(Q3UIDIR)/ui_removebots.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_teamorders.asm : $(Q3UIDIR)/ui_teamorders.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_cdkey.asm : $(Q3UIDIR)/ui_cdkey.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/ui_mods.asm : $(Q3UIDIR)/ui_mods.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/bg_misc.asm : $(GDIR)/bg_misc.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/bg_lib.asm : $(GDIR)/bg_lib.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/q_math.asm : $(GDIR)/q_math.c; $(DO_UI_LCC)
$(Q3UIDIR)/vm/q_shared.asm : $(GDIR)/q_shared.c; $(DO_UI_LCC)

#############################################################################
# CGAME
#############################################################################

CGOBJ = \
	$(SRCDIR)/cgame/bg_lib.o \
	$(SRCDIR)/cgame/bg_misc.o \
	$(SRCDIR)/cgame/bg_pmove.o \
	$(SRCDIR)/cgame/bg_slidemove.o \
	$(SRCDIR)/cgame/cg_consolecmds.o \
	$(SRCDIR)/cgame/cg_draw.o \
	$(SRCDIR)/cgame/cg_drawtools.o \
	$(SRCDIR)/cgame/cg_effects.o \
	$(SRCDIR)/cgame/cg_ents.o \
	$(SRCDIR)/cgame/cg_event.o \
	$(SRCDIR)/cgame/cg_info.o \
	$(SRCDIR)/cgame/cg_localents.o \
	$(SRCDIR)/cgame/cg_main.o \
	$(SRCDIR)/cgame/cg_marks.o \
	$(SRCDIR)/cgame/cg_players.o \
	$(SRCDIR)/cgame/cg_playerstate.o \
	$(SRCDIR)/cgame/cg_predict.o \
	$(SRCDIR)/cgame/cg_scoreboard.o \
	$(SRCDIR)/cgame/cg_servercmds.o \
	$(SRCDIR)/cgame/cg_snapshot.o \
	$(SRCDIR)/cgame/cg_view.o \
	$(SRCDIR)/cgame/cg_weapons.o \
	$(SRCDIR)/cgame/q_math.o \
	$(SRCDIR)/cgame/q_shared.o

$(SRCDIR)/cgame$(ARCH).$(SHLIBEXT) : $(CGOBJ)
	$(CC) $(CFLAGS) $(SHLIBLDFLAGS) -o $@ $(CGOBJ)

$(SRCDIR)/cgame/bg_lib.o : $(GDIR)/bg_lib.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/bg_misc.o : $(GDIR)/bg_misc.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/bg_pmove.o : $(GDIR)/bg_pmove.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/bg_slidemove.o : $(GDIR)/bg_slidemove.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_consolecmds.o : $(CGDIR)/cg_consolecmds.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_draw.o : $(CGDIR)/cg_draw.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_drawtools.o : $(CGDIR)/cg_drawtools.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_effects.o : $(CGDIR)/cg_effects.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_ents.o : $(CGDIR)/cg_ents.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_event.o : $(CGDIR)/cg_event.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_info.o : $(CGDIR)/cg_info.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_localents.o : $(CGDIR)/cg_localents.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_main.o : $(CGDIR)/cg_main.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_marks.o : $(CGDIR)/cg_marks.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_players.o : $(CGDIR)/cg_players.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_playerstate.o : $(CGDIR)/cg_playerstate.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_predict.o : $(CGDIR)/cg_predict.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_scoreboard.o : $(CGDIR)/cg_scoreboard.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_servercmds.o : $(CGDIR)/cg_servercmds.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_snapshot.o : $(CGDIR)/cg_snapshot.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_view.o : $(CGDIR)/cg_view.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/cg_weapons.o : $(CGDIR)/cg_weapons.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/q_math.o : $(GDIR)/q_math.c; $(DO_SHLIB_CC) 
$(SRCDIR)/cgame/q_shared.o : $(GDIR)/q_shared.c; $(DO_SHLIB_CC) 

#############################################################################
# UI
#############################################################################

UIOBJ = \
	$(SRCDIR)/ui/bg_lib.o \
	$(SRCDIR)/ui/bg_misc.o \
	$(SRCDIR)/ui/ui_addbots.o \
	$(SRCDIR)/ui/ui_atoms.o \
	$(SRCDIR)/ui/ui_cinematics.o \
	$(SRCDIR)/ui/ui_confirm.o \
	$(SRCDIR)/ui/ui_connect.o \
	$(SRCDIR)/ui/ui_controls2.o \
	$(SRCDIR)/ui/ui_credits.o \
	$(SRCDIR)/ui/ui_demo2.o \
	$(SRCDIR)/ui/ui_display.o \
	$(SRCDIR)/ui/ui_gameinfo.o \
	$(SRCDIR)/ui/ui_ingame.o \
	$(SRCDIR)/ui/ui_loadconfig.o \
	$(SRCDIR)/ui/ui_main.o \
	$(SRCDIR)/ui/ui_menu.o \
	$(SRCDIR)/ui/ui_mfield.o \
	$(SRCDIR)/ui/ui_network.o \
	$(SRCDIR)/ui/ui_playermodel.o \
	$(SRCDIR)/ui/ui_players.o \
	$(SRCDIR)/ui/ui_playersettings.o \
	$(SRCDIR)/ui/ui_preferences.o \
	$(SRCDIR)/ui/ui_qmenu.o \
	$(SRCDIR)/ui/ui_saveconfig.o \
	$(SRCDIR)/ui/ui_serverinfo.o \
	$(SRCDIR)/ui/ui_servers2.o \
	$(SRCDIR)/ui/ui_setup.o \
	$(SRCDIR)/ui/ui_sound.o \
	$(SRCDIR)/ui/ui_sparena.o \
	$(SRCDIR)/ui/ui_specifyserver.o \
	$(SRCDIR)/ui/ui_splevel.o \
	$(SRCDIR)/ui/ui_sppostgame.o \
	$(SRCDIR)/ui/ui_spskill.o \
	$(SRCDIR)/ui/ui_startserver.o \
	$(SRCDIR)/ui/ui_team.o \
	$(SRCDIR)/ui/ui_video.o \
	\
	$(SRCDIR)/ui/q_math.o \
	$(SRCDIR)/ui/q_shared.o

$(SRCDIR)/ui$(ARCH).$(SHLIBEXT) : $(UIOBJ)
	$(CC) $(CFLAGS) $(SHLIBLDFLAGS) -o $@ $(UIOBJ)

$(SRCDIR)/ui/bg_lib.o : $(GDIR)/bg_lib.c; $(DO_CC) 
$(SRCDIR)/ui/bg_misc.o : $(GDIR)/bg_misc.c; $(DO_CC) 
$(SRCDIR)/ui/ui_addbots.o : $(UIDIR)/ui_addbots.c; $(DO_CC) 
$(SRCDIR)/ui/ui_atoms.o : $(UIDIR)/ui_atoms.c; $(DO_CC) 
$(SRCDIR)/ui/ui_cinematics.o : $(UIDIR)/ui_cinematics.c; $(DO_CC) 
$(SRCDIR)/ui/ui_confirm.o : $(UIDIR)/ui_confirm.c; $(DO_CC) 
$(SRCDIR)/ui/ui_connect.o : $(UIDIR)/ui_connect.c; $(DO_CC) 
$(SRCDIR)/ui/ui_controls2.o : $(UIDIR)/ui_controls2.c; $(DO_CC) 
$(SRCDIR)/ui/ui_credits.o : $(UIDIR)/ui_credits.c; $(DO_CC) 
$(SRCDIR)/ui/ui_demo2.o : $(UIDIR)/ui_demo2.c; $(DO_CC) 
$(SRCDIR)/ui/ui_display.o : $(UIDIR)/ui_display.c; $(DO_CC) 
$(SRCDIR)/ui/ui_gameinfo.o : $(UIDIR)/ui_gameinfo.c; $(DO_CC) 
$(SRCDIR)/ui/ui_ingame.o : $(UIDIR)/ui_ingame.c; $(DO_CC) 
$(SRCDIR)/ui/ui_loadconfig.o : $(UIDIR)/ui_loadconfig.c; $(DO_CC) 
$(SRCDIR)/ui/ui_main.o : $(UIDIR)/ui_main.c; $(DO_CC) 
$(SRCDIR)/ui/ui_menu.o : $(UIDIR)/ui_menu.c; $(DO_CC) 
$(SRCDIR)/ui/ui_mfield.o : $(UIDIR)/ui_mfield.c; $(DO_CC) 
$(SRCDIR)/ui/ui_network.o : $(UIDIR)/ui_network.c; $(DO_CC) 
$(SRCDIR)/ui/ui_playermodel.o : $(UIDIR)/ui_playermodel.c; $(DO_CC) 
$(SRCDIR)/ui/ui_players.o : $(UIDIR)/ui_players.c; $(DO_CC) 
$(SRCDIR)/ui/ui_playersettings.o : $(UIDIR)/ui_playersettings.c; $(DO_CC) 
$(SRCDIR)/ui/ui_preferences.o : $(UIDIR)/ui_preferences.c; $(DO_CC) 
$(SRCDIR)/ui/ui_qmenu.o : $(UIDIR)/ui_qmenu.c; $(DO_CC) 
$(SRCDIR)/ui/ui_quit.o : $(UIDIR)/ui_quit.c; $(DO_CC) 
$(SRCDIR)/ui/ui_saveconfig.o : $(UIDIR)/ui_saveconfig.c; $(DO_CC) 
$(SRCDIR)/ui/ui_serverinfo.o : $(UIDIR)/ui_serverinfo.c; $(DO_CC) 
$(SRCDIR)/ui/ui_servers2.o : $(UIDIR)/ui_servers2.c; $(DO_CC) 
$(SRCDIR)/ui/ui_setup.o : $(UIDIR)/ui_setup.c; $(DO_CC) 
$(SRCDIR)/ui/ui_sound.o : $(UIDIR)/ui_sound.c; $(DO_CC) 
$(SRCDIR)/ui/ui_sparena.o : $(UIDIR)/ui_sparena.c; $(DO_CC) 
$(SRCDIR)/ui/ui_specifyserver.o : $(UIDIR)/ui_specifyserver.c; $(DO_CC) 
$(SRCDIR)/ui/ui_splevel.o : $(UIDIR)/ui_splevel.c; $(DO_CC) 
$(SRCDIR)/ui/ui_sppostgame.o : $(UIDIR)/ui_sppostgame.c; $(DO_CC) 
$(SRCDIR)/ui/ui_spskill.o : $(UIDIR)/ui_spskill.c; $(DO_CC) 
$(SRCDIR)/ui/ui_startserver.o : $(UIDIR)/ui_startserver.c; $(DO_CC) 
$(SRCDIR)/ui/ui_team.o : $(UIDIR)/ui_team.c; $(DO_CC) 
$(SRCDIR)/ui/ui_video.o : $(UIDIR)/ui_video.c; $(DO_CC) 
$(SRCDIR)/ui/q_math.o : $(GDIR)/q_math.c; $(DO_SHLIB_CC) 
$(SRCDIR)/ui/q_shared.o : $(GDIR)/q_shared.c; $(DO_SHLIB_CC) 

#############################################################################
# MISC
#############################################################################

clean:
	rm -f $(GVMASM) $(CGVMASM)
